favicon: null
name: Ford Roosevelt
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2346938
  brandStrength: 0.5708916
  lightness: 0.3431793
  brandColors:
    - '#111111'
    - '#2E2E2E'
    - '#4E4E4E'
    - '#8C8C8C'
    - '#C9C9C9'
  rhythmicContrast: 0.4914071
typography_spectrum: 0.1076848122756928
layout_spectrum: 0.785968708107248
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
